### ISSUE TITLE
how to use fbx files to draw characters?

### ISSUE THREAD

**Issue by DYF-AI** [wixette/font-to-3d-models#1]
This is a great job, I have produced fbx files, but I don’t know how to use fbx files to draw characters,Can you provide some examples？

**Comment by wixette** [comment]
I imported the fbx files into Unity as character prefabs, to build an in-game 3d bulletin board.

There are many ways to render the character models into images if you want. E.g.,

a) simply open the fbx file in an online 3d model viewer, like this one, https://www.creators3d.com/online-viewer.
b) import the models into a Blender scene and render the scene into images.
c) if you prefer doing that by coding, JavaScript + threejs.org can surely help.

Hope this helps.
